/**
 * BombBomb
 * We make it easy to use simple video to build relationships
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/JerichoConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/JerichoConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.BombbombNodejsOpenapi) {
      root.BombbombNodejsOpenapi = {};
    }
    root.BombbombNodejsOpenapi.TeamsApi = factory(root.BombbombNodejsOpenapi.ApiClient, root.BombbombNodejsOpenapi.JerichoConfiguration);
  }
}(this, function(ApiClient, JerichoConfiguration) {
  'use strict';

  /**
   * Teams service.
   * @module api/TeamsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TeamsApi. 
   * @alias module:api/TeamsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the queueJerichoSend operation.
     * @callback module:api/TeamsApi~queueJerichoSendCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JerichoConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a Jericho send.
     * Sends email content on behalf of members of a client group. There are two forms this send can take:         Static Email, and Video Prompt. Static emails require only an emailId.         Video Prompts build emails dynamically and require most of the other fields.         You must be an administrator of a Team Account to use this method.
     * @param {module:model/JerichoConfiguration} config JSON representing a Jericho configuration
     * @param {String} teamId The ID of the team.
     * @param {module:api/TeamsApi~queueJerichoSendCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JerichoConfiguration}
     */
    this.queueJerichoSend = function(config, teamId, callback) {
      var postBody = config;

      // verify the required parameter 'config' is set
      if (config == undefined || config == null) {
        throw "Missing the required parameter 'config' when calling queueJerichoSend";
      }

      // verify the required parameter 'teamId' is set
      if (teamId == undefined || teamId == null) {
        throw "Missing the required parameter 'teamId' when calling queueJerichoSend";
      }


      var pathParams = {
        'teamId': teamId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['BBOAuth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = JerichoConfiguration;

      return this.apiClient.callApi(
        '/team/{teamId}/jericho', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
