/**
 * BombBomb
 * We make it easy to use simple video to build relationships
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BombbombNodejsOpenapi);
  }
}(this, function(expect, BombbombNodejsOpenapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BombbombNodejsOpenapi.JerichoConfiguration();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JerichoConfiguration', function() {
    it('should create an instance of JerichoConfiguration', function() {
      // uncomment below and update the code to test JerichoConfiguration
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be.a(BombbombNodejsOpenapi.JerichoConfiguration);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property clientGroupId (base name: "clientGroupId")', function() {
      // uncomment below and update the code to test the property clientGroupId
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property sendDate (base name: "sendDate")', function() {
      // uncomment below and update the code to test the property sendDate
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property isPrompt (base name: "isPrompt")', function() {
      // uncomment below and update the code to test the property isPrompt
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property emailId (base name: "emailId")', function() {
      // uncomment below and update the code to test the property emailId
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property promptSubject (base name: "promptSubject")', function() {
      // uncomment below and update the code to test the property promptSubject
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property promptBody (base name: "promptBody")', function() {
      // uncomment below and update the code to test the property promptBody
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property emailSubject (base name: "emailSubject")', function() {
      // uncomment below and update the code to test the property emailSubject
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property emailBody (base name: "emailBody")', function() {
      // uncomment below and update the code to test the property emailBody
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

    it('should have the property sendWithoutVideo (base name: "sendWithoutVideo")', function() {
      // uncomment below and update the code to test the property sendWithoutVideo
      //var instane = new BombbombNodejsOpenapi.JerichoConfiguration();
      //expect(instance).to.be();
    });

  });

}));
